### PR TITLE
use utf-8 encoding, closes #21

### LINKED ISSUE #21: Utils.b64stringify() is called wrong
It does not support a second `encoding` argument.

https://github.com/hapijs/jwt/blob/634ce2f79b0bf684d35519ff63fa9553a6896517/lib/token.js#L44

https://github.com/hapijs/jwt/blob/ca6bad9165b6f7cd781aca5f8ab9f5927b8c9e47/lib/utils.js#L9

### PR DESCRIPTION
**Pull request by devinstewart**

### CODE REVIEW

File: lib/token.js [hunk 1]
```diff
@@ -250,7 +250,7 @@ internals.error = function (message, artifacts) {
 
 internals.b64decode = function (string) {
 
-    return Buffer.from(string, 'base64').toString('binary');
+    return Buffer.from(string, 'base64').toString();
```
Comment (devinivy) [inline lib/token.js:253]: Apologies that this PR hasn't gotten the attention it deserves!  I have a question here— do you have a sense for why this latin1 encoding was used in the first place?  It stands out a little bit to me that it was going out of its way to avoid utf-8, which seems like it would have been more natural.  Mostly want to ensure there's not some security or portability issue we're creating here.

File: lib/token.js [hunk 2]
```diff
@@ -46,7 +46,7 @@ exports.generate = function (payload, secret, options = {}) {
     }
 
     const header = Object.assign(baseHeader, options.header);
-    const value = `${Utils.b64stringify(header)}.${Utils.b64stringify(content, options.encoding || 'utf8')}`;
+    const value = `${Utils.b64stringify(header)}.${Utils.b64stringify(content)}`;
```
Comment (devinivy) [inline lib/token.js:49]: This option is used here, and should be able to be removed now: https://github.com/hapijs/jwt/blob/835ac389516e77dd6d4f82e9c318a62375072f16/test/token.js#L107

File: lib/token.js (hunk 1 above)
Comment (devinstewart) [reply lib/token.js:253]: Yeah, I looked into this and to the best guess it goes back to the `jws` module that has the lines.

```javascript
var encodedHeader = base64url(toString(header), 'binary');
var encodedPayload = base64url(toString(payload), encoding)
```

I followed the commits back they were originally both 'binary'.  When encoding was added as a feature it was only put on the `payload` and not the `header`.

My guess is that `jsonwebtoken` does not allow you to add custom fields to the header, so there was no need to use utf8, since everything standard in the header is latin1.  It was my thought that since our `jwt` allows putting custom objects in the header we should use the JavaScript standard of utf8.

If the RFC I saw this:
_Base64url encoding the bytes of the UTF-8 representation of the JWS Header yields this Encoded JWS Header value:_

Which made me believe there is nothing against the spec. 

 Either way, LMK.  I am fine with leaving it as is or removing it.  The original issue was that  we were calling `Utils.b64stringify()` with a 2nd argument, which has been fixed above.

File: lib/token.js (hunk 2 above)
Comment (devinstewart) [reply lib/token.js:49]: removed

**Review by devinivy — APPROVED** [review]
Looks good, thank you!  I am going to include this in the upcoming major, out of an abundance of caution more than anything else.

**Comment by devinivy** [comment]
Resolves #21.
